[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/*.jsx"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/*.css"
  to = "/index.html"
  status = 200
  force = true
